services:
  application_postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: historical_db
      POSTGRES_USER: icanooo
      POSTGRES_PASSWORD: thisisapassword
    volumes: 
      - historical_db_volumes:/var/lib/postgresql/data
      - ./scripts/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U icanooo -d historical_db"]
      interval: 5s
      timeout: 5s
      retries: 5

    networks:
      - jenkins-net

  insert_location:
    build:
      context: .
      dockerfile: Dockerfile.insert_location
    depends_on:
      application_postgres:
        condition: service_healthy
    volumes:
      - ./scripts:/app
    command: ["python", "insert_location.py"]
    networks:
      - jenkins-net
   
  jenkins:
    build: .
    container_name: jenkins
    ports:
      - "8080:8080"
      - "10000:10000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - ./scripts:/var/jenkins_home/scripts
    restart: unless-stopped
    networks:
      - jenkins-net

        
volumes:
  historical_db_volumes:
  jenkins_home: 

networks:
  jenkins-net:
