services:
  application_postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: historical_db
      POSTGRES_USER: icanooo
      POSTGRES_PASSWORD: thisisapassword
    volumes: 
      - historical_db_volumes:/var/lib/postgresql/data
    networks:
      - jenkins-net

  jenkins:
    build: .
    container_name: jenkins
    ports:
      - "8080:8080"
      - "10000:10000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - ./sql:/var/jenkins_home/sql
    restart: unless-stopped
    networks:
      - jenkins-net

volumes:
  historical_db_volumes:
  jenkins_home: 

networks:
  jenkins-net:
